### ISSUE TITLE
Occasional missing inter-residue bonds with `altloc="occupancy"`

### ISSUE THREAD

**Issue by RafiBrent** [biotite-dev/biotite#777]
When calling `biotite.structure.io.pdbx.get_structure` with `altloc='occupancy'`,  there is an occasional bug where standard inter-residue polymer bonds are missing.

This happens because bonds are computed before filtering by altloc, but `biotite.structure.bonds._connect_inter_residue` will only use the first occurrence of a given `atom_name` when creating polymer bonds. Because of this, if the first-occurring version of an atom in the structure is not the highest-occupancy version, then when the first occurrence is filtered out the polymer bond is lost with it.

For a reproducing example, see PDB ID 3kz8:

```python
import numpy as np
from biotite.structure.io import pdbx

cif_file = pdbx.CIFFile.read("/path/to/3kz8.cif")
atom_array = pdbx.get_structure(cif_file.block, altloc="occupancy", use_author_fields=False, include_bonds=True)[0]

print(atom_array.atom_name[477], atom_array.res_name[477]) # This is a backbone carbonyl carbon atom in an amino acid
print(atom_array.atom_name[480], atom_array.res_name[480]) # This is a backbone nitrogen atom in an amino acid
print(atom_array.chain_id[477], atom_array.chain_id[480]) # They are in the same chain
bonded_idces = np.array(atom_array.bonds.get_bonds(477)[0]) 
print(bonded_idces) # However, they are not bonded!
```

(In the above example, there is also a missing inter-residue bond between atoms 482 and 488.)

Happy to provide any other information that would be helpful, and thanks so much for the fantastic library!

**Comment by padix-key** [comment]
Hi, thanks for the thorough analysis! Your reasoning makes absolutely sense. I suspect this is easily fixed by moving the line

https://github.com/biotite-dev/biotite/blob/5465b750d843c11231845350e54c3bdbeb99055d/src/biotite/structure/io/pdbx/convert.py#L413

prior to the bond computation.

Would you like to create the fix, or should I prepare a PR? In case you tackle this issue: You can use `3o5r.cif` for testing this: This structure is already in the repo and has also altlocs in the protein chain.

**Comment by RafiBrent** [comment]
Sounds good! That should definitely fix the issue. What do you think is the best way to handle the case of `altloc='all'` and `include_bonds=True`? Currently `connect_via_residue_names` will create all intra-residue bonds involving any of the altloc atoms, but will only use the first occurrence of each atom when creating canonical inter-residue bonds. The simplest thing might be to just give an error in this case, but not sure if there's a potential use-case -- what do you think?

**Comment by padix-key** [comment]
> The simplest thing might be to just give an error in this case

Yes, I agree. The primary purpose of `altloc='all'` is to give the user the ability to perform some custom filtering. At least intra-residue bonds and canonical inter-residue bonds can also easily be added after filtering with `connect_via_residue_names()`.

**Comment by RafiBrent** [comment]
Ok sounds good. I was initially planning to just handle this myself, but after making these and another fix (had to allow `parse_inter_residue_bonds` to create a `BondList` with a different `atom_count` than what was in the initial `atom_site`), I'm still getting a few errors in pre-existing tests. Happy to provide more detail below, but they're mostly related to minor inconsistencies after a read-write step, and only occur for a small fraction of the test files. 

I'm thinking that I might be a bit out of my depth in terms of familiarity with the rest of the codebase, and was wondering if you'd be willing to take a look at this to see what additional fixes might be necessary. Happy to share my changes and new test if that would be helpful, or if you'd rather redo it everything should be pretty straightforward up to this point. Let me know what you'd prefer, and thanks for your responsiveness about this!

**Comment by padix-key** [comment]
Yes, feel free to open a PR with your current changes, and I'll take care of the remaining bits.

**Comment by RafiBrent** [comment]
Sounds good, thanks! Just added the PR.

**Comment by padix-key** [comment]
Fixed by #781
